Repository VividClothes/VividClothes, pull requests merged in 2022-06, with the labels that each got.

#13 220623 passport로 로컬 로그인 구현
  package-lock.json
  package.json
  src/app.js
  src/db/models/user-model.js
  src/db/schemas/auth-schema.js
  src/db/schemas/user-schema.js
  src/middlewares/login-required.js
  src/middlewares/sendEmail.js
  src/middlewares/user-validator.js
  src/middlewares/userRole-check.js
  src/passport/index.js
  src/passport/kakao.js
  src/passport/strategies/local-strategy.js
  src/routers/user-router.js
  src/services/google-passport.js
  src/services/google.js
  src/services/user-service.js
  src/utils/generate-random-password.js
Labels: 가영, 백엔드, p2

#15 220625 카카오 로그인
  package-lock.json
  package.json
  src/app.js
  src/db/schemas/user-schema.js
  src/middlewares/user-validator.js
  src/passport/index.js
  src/passport/strategies/kakao-strategy.js
  src/passport/strategies/local-strategy.js
  src/routers/user-router.js
  src/services/user-service.js
  src/views/login/login.html
  src/views/login/login.js
Labels: 가영, 백엔드, p1

#26 design: 모달 창 반응형 수정
  src/views/shared/components/modal/modal-style.js
  src/views/shared/components/modal/product-modal-form.js
Labels: 프론트엔드
